### ISSUE TITLE
Company swag sharing channel

### ISSUE THREAD

**Issue by st-tran** [cscareers-dev/suggestions#3]
### What is your suggestion?

```shell
A company swag sharing channel to share what free things companies send for internships, events, etc
```

### What is the value add for adding this to the Discord server?

```shell
It'd be an interesting datapoint
```

**Comment by joeydotdev** [comment]
Discussed this with the admins and we are all pretty much in agreement that we don't want the community to devolve into being a romanticization of companies. Implementing a channel like this is devolving into that path.

The goal of the community is to best equip job-seekers with information they should know about in the recruiting process, and we don't think company swag is a part of this.
