### ISSUE TITLE
Separate Leetcode-Bot Channels (Intern/New grad) 

### ISSUE THREAD

**Issue by Sharvilpr23** [cscareers-dev/suggestions#7]
### What is your suggestion?

```shell
I feel it would be helpful to have two separate channels for the leetcode-bot; one with most frequent Qs asked in intern interviews and one with most frequent Qs asked in new grad.
```

### What is the value add for adding this to the Discord server?

```shell
It'll help folks focus more time on the Qs with a higher chance to be asked in an interview (not that solving new grad LC questions wouldn't help).
```

**Comment by joeydotdev** [comment]
We could, but is something we actively decided against as an admin team for the following reasons:
* Our data source does not provide granularity for the context in which a problem is asked in. Company level questions is the best we can get unless we want to crowd-source our own which we don't. 

* IMO, is crossing the border of cheating. The difference between what we have now and what you're suggesting is that the company level questions are preparing you for the average-difficulty of interview agonistic of level. Some of the questions the bot reports (I would imagine the majority of them but cannot verify this) are all seen in interviews for mid-level to senior roles. If you are able to effectively solve those questions, folks should be well equipped to solve the problems for their intern/new-grad interviews.

The idea with the bot is to get you at the bar for the company you're interviewing at - and knowing the *exact* questions for a specific level interview isn't a requirement for that.
