### ISSUE TITLE
Column Sorting

### ISSUE THREAD

**Issue by tristingreenstein** [cscareers-dev/suggestions#8]
### What is your suggestion?

```shell
https://www.cscareers.dev/process-tracking/2022-new-grad

Allow user to organize table by selecting headers. Click offer column to have it sort by companies with most to least offers.
```

### What is the value add for adding this to the website?

```shell
Easier to see what companies are hiring more than rejecting
```

### Additional context

![image](https://user-images.githubusercontent.com/43738971/141211678-cab115dc-4547-4c9a-8639-32357bbc5b27.png)

**Comment by joeydotdev** [comment]
Agree. maybe some sort of pagination or filtering based off company types seen in https://cscareers.dev/companies would be useful too

**Comment by joeydotdev** [comment]
Implemented
